# The Site Configuration

remote_theme: cotes2020/jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Asia/Shanghai

title: Your Blog Title
description: A description of your blog.
url: "https://pushwithak.github.io/blog"

# Social information
social:
  name: Pushwitha Krishnappa
  links:
    - https://github.com/pushwithak

# GitHub Pages only supports a subset of plugins available in Jekyll,
# specify plugins you're using, for example:
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme_mode: light
paginate: 10
